/* Generated By:JavaCC: Do not edit this line. MdlParser.java */

import java.util.*;

import parser.*;
import parseTables.*;

public class mdl 
{
  public static void main(String args[]) throws ParseException 
    {
	ArrayList a;	

	MdlParser parser = new MdlParser(System.in);
	parser.start();
	a = parser.getOps();

	System.out.println("Opcodes:");
	Iterator i = a.iterator();
	while (i.hasNext())
	    {
		System.out.println(i.next());
	    }
	System.out.println("\n\n");
	SymTab s = parser.getSymTab();
	Set kset = s.keySet();
	i=kset.iterator();
	System.out.println("Symbol Table:");
	while (i.hasNext())
	    {
		String key = (String)i.next();
		Object value=s.get(key);
		System.out.println(""+key+"="+value);
	    }
  }
}
